name: Opde Build

on:
  pull_request:

jobs:
  worker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86
            subtarget: "64"

    steps:
      - name: Set up Environment Variable
        run: |
          OP_BASE_DIR="$(realpath ${{github.workspace}}/..)"
          OP_DIR="$OP_BASE_DIR/openwrt"
          echo "Openwrt SDK Dir: $OP_DIR"
          mkdir $OP_DIR
          echo "OP_DIR=$OP_DIR" >> $GITHUB_ENV
          BRANCH="${GITHUB_BASE_REF#refs/heads/}"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          OPDE_VER="${{matrix.target}}_${{matrix.subtarget}}-$BRANCH"
          echo "OPDE_VER=$OPDE_VER" >> $GITHUB_ENV
          echo "Building for $OPDE_VER"
          FEED_NAME="packages"
          FEED_GIT="https://github.com/immortalwrt/packages.git"
          echo "FEED_NAME=$FEED_NAME" >> $GITHUB_ENV
          echo "FEED_GIT=$FEED_GIT" >> $GITHUB_ENV
          echo "Feed: $FEED_NAME $FEED_GIT"
          DOCKER="docker run -v $PWD:/feed -v $OP_DIR:/openwrt opde:worker"
          echo "Docker command: $DOCKER"
          echo "DOCKER=$DOCKER" >> $GITHUB_ENV
      #- name: Free disk space
      #  run: |
      #    sudo -E swapoff -a
      #    sudo -E rm -f /swapfile
      #    sudo -E docker image prune -a -f
      #    sudo -E snap set system refresh.retain=2
      #    sudo -E apt-get -y purge azure* dotnet* firefox ghc* google* hhvm llvm* mono* mysql* openjdk* php* zulu* powershell* msodbc*
      #    sudo -E apt-get -y autoremove --purge
      #    sudo -E apt-get clean
      #    sudo -E rm -rf /usr/share/dotnet /usr/local/lib/android/sdk /etc/mysql /etc/php /usr/local/share/boost
      #    [ -n "$AGENT_TOOLSDIRECTORY" ] && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      #    df -h
      - name: Checkout Packages repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Detect Changed Makefile
        run: |
          git diff --diff-filter=d --name-only HEAD~ | \
          grep -v ".*/src/Makefile" | \
          sed -e 's@.*/\(.\+\)/Makefile@package/feeds/packages/\1@' | \
          tee changelist
      - name: pull docker image
        run: |
          docker pull immortalwrt/opde:worker-$OPDE_VER
          docker tag immortalwrt/opde:worker-$OPDE_VER opde:worker
          docker images
      - name: Copy SDK
        run: |
          docker run -v $OP_DIR:/openwrt_bak opde:worker sudo chown opde:opde -R /openwrt_bak
          docker run -v $OP_DIR:/openwrt_bak opde:worker rsync -av /openwrt/ /openwrt_bak
      - name: replace feed
        run: |
          $DOCKER sudo chown opde:opde -R /feed
          $DOCKER sed -i "s%src-git $FEED_NAME $FEED_GIT%src-link $FEED_NAME /feed%" feeds.conf.default
          $DOCKER cat feeds.conf.default
      - name: Opde feeds
        run: |
          $DOCKER opde feeds
          $DOCKER opde config
      - name: Find affected packages
        run: | # TODO: move to `opde config`
          $DOCKER touch .opde/addon.conf
          $DOCKER opde find-affected /feed/changelist -post -o .opde/addon.conf
          $DOCKER cat .opde/addon.conf
      - name: Opde config
        run: $DOCKER opde config -i .opde/addon.conf
      - name: Show config
        run: $DOCKER cat .opde/min-config.in
      - name: Opde download
        run: $DOCKER opde download
      - name: Opde build
        run: $DOCKER opde build
      - name: Fix premission
        run: sudo chown $(id -u -n):$(id -g -n) -R $OP_DIR

      - name: Check
        run: |
          ERR_PACKS=$(cat .opde/log.out | grep ERROR | grep -v fullconenat || true)
          echo $ERR_PACKS
          [[ $errors == "" ]]

      - name: Prepare upload
        if: always()
        run: |
          mkdir /tmp/opdelogs && cp -rf $OP_DIR/.opde $OP_DIR/logs /tmp/opdelogs
          mv $OP_DIR/bin /tmp/opdebin
          rm $OP_DIR -rf
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Log
          path: /tmp/opdelogs
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Packages
          path: /tmp/opdebin
      #- name: debug # docker run -it -v $PWD:/openwrt immortalwrt/opde:base bash
      #  uses: mxschmitt/action-tmate@v2
      #  if: failure()
